name: personal_hud_lite
description: "Motorcycle HUD prototype — sci-fi Jarvis-style overlay."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sensors_plus: ^6.0.0
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  camera: ^0.11.0
  permission_handler: ^11.3.1
  google_maps_flutter: ^2.9.0
  geolocator: ^13.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
